from typing import Optional

class Var:
    def expr(self) -> LinExprPy: ...
    def leq(self, other: LinExprPy) -> ConstraintPy: ...
    def geq(self, other: LinExprPy) -> ConstraintPy: ...
    def eq(self, other: LinExprPy) -> ConstraintPy: ...
    def __mul__(self, rhs: float) -> LinExprPy: ...
    def __rmul__(self, lhs: float) -> LinExprPy: ...
    def __add__(self, other: Var | LinExprPy) -> LinExprPy: ...
    def __radd__(self, other: LinExprPy) -> LinExprPy: ...

class LinExprPy:
    def eq(self, rhs: float) -> ConstraintPy: ...
    def leq(self, rhs: float) -> ConstraintPy: ...
    def geq(self, rhs: float) -> ConstraintPy: ...
    def __add__(self, other: LinExprPy) -> LinExprPy: ...
    def __mul__(self, rhs: float) -> LinExprPy: ...
    def __rmul__(self, lhs: float) -> LinExprPy: ...

class ConstraintPy: ...

class Solution:
    @property
    def objective_value(self) -> Optional[float]: ...
    def value(self, var: Var) -> float: ...
    def __repr__(self) -> str: ...

class Model:
    def __new__(cls) -> Model: ...
    def add_var(
        self,
        name: Optional[str] = None,
        lb: Optional[float] = None,
        ub: Optional[float] = None,
    ) -> Var: ...
    def minimize(self, expr: LinExprPy, name: Optional[str] = None) -> None: ...
    def maximize(self, expr: LinExprPy, name: Optional[str] = None) -> None: ...
    def add_constraint(self, c: ConstraintPy) -> None: ...
    def solve(self) -> Solution: ...
