from typing import Optional, Union

Operand = Union["Var", "LinExprPy", float]

class Var:
    def expr(self) -> "LinExprPy": ...
    def leq(self, other: Operand) -> "ConstraintPy": ...
    def geq(self, other: Operand) -> "ConstraintPy": ...
    def eq(self, other: Operand) -> "ConstraintPy": ...
    def __le__(self, other: Operand) -> "ConstraintPy": ...
    def __ge__(self, other: Operand) -> "ConstraintPy": ...
    def __eq__(self, other: Operand) -> "ConstraintPy": ...  # type: ignore
    def __add__(self, other: Operand) -> "LinExprPy": ...
    def __radd__(self, other: Operand) -> "LinExprPy": ...
    def __sub__(self, other: Operand) -> "LinExprPy": ...
    def __rsub__(self, other: Operand) -> "LinExprPy": ...
    def __mul__(self, rhs: float) -> "LinExprPy": ...
    def __rmul__(self, lhs: float) -> "LinExprPy": ...
    def __truediv__(self, rhs: float) -> "LinExprPy": ...
    def __neg__(self) -> "LinExprPy": ...

class LinExprPy:
    def leq(self, other: Operand) -> "ConstraintPy": ...
    def geq(self, other: Operand) -> "ConstraintPy": ...
    def eq(self, other: Operand) -> "ConstraintPy": ...
    def __le__(self, other: Operand) -> "ConstraintPy": ...
    def __ge__(self, other: Operand) -> "ConstraintPy": ...
    def __eq__(self, other: Operand) -> "ConstraintPy": ...  # type: ignore
    def __add__(self, other: Operand) -> "LinExprPy": ...
    def __radd__(self, other: Operand) -> "LinExprPy": ...
    def __sub__(self, other: Operand) -> "LinExprPy": ...
    def __rsub__(self, other: Operand) -> "LinExprPy": ...
    def __mul__(self, rhs: float) -> "LinExprPy": ...
    def __rmul__(self, lhs: float) -> "LinExprPy": ...
    def __truediv__(self, rhs: float) -> "LinExprPy": ...
    def __neg__(self) -> "LinExprPy": ...

class ConstraintPy: ...

class Solution:
    @property
    def objective_value(self) -> Optional[float]: ...
    def value(self, var: Var) -> float: ...
    def __repr__(self) -> str: ...

class Model:
    def __new__(cls) -> "Model": ...
    def add_var(
        self,
        name: Optional[str] = None,
        lb: Optional[float] = None,
        ub: Optional[float] = None,
    ) -> Var: ...
    def minimize(self, expr: LinExprPy, name: Optional[str] = None) -> None: ...
    def maximize(self, expr: LinExprPy, name: Optional[str] = None) -> None: ...
    def add_constraint(self, c: ConstraintPy) -> None: ...
    def solve(self) -> Solution: ...
