# List tasks available
default:
    @just --list --list-prefix " - "

# Build the project using cargo to create a WebAssembly module
build:
    cargo build --release --target wasm32-unknown-unknown
    cp ../../target/wasm32-unknown-unknown/release/cnvx.wasm examples/cnvx.wasm

# Compile an example file
compile file="examples/power.typ": build
    typst compile {{ file }}

# Clean the build artifacts
clean:
    cargo clean
    rm -rf examples/cnvx.wasm
